version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: 'chore(packages)'
    labels:
      - 'npm'
      - 'dependencies'
    open-pull-requests-limit: 100
    rebase-strategy: auto
    reviewers:
      - 'enercity-ag/nd-it-b-devops-web'
    groups:
      node-packages:
        patterns:
          - '*'
    target-branch: main
  - package-ecosystem: 'github-actions'
    directory: '/'
    commit-message:
      prefix: 'chore(workflow)'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 100
    rebase-strategy: auto
    reviewers:
      - 'enercity-ag/nd-it-b-devops-web'
    groups:
      node-packages:
        patterns:
          - '*'
