name: Publish to npm

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js environment
        uses: actions/setup-node@v5
        with:
          node-version: '20.x'

      - name: Set version
        run: |
          git config user.email "noreply@enercity-netz.de"
          git config user.name "enercity DevOps" 
          npm --no-git-tag-version version ${{github.ref_name}}

      - name: Install dependencies
        run: npm ci

      - name: Publish package to npm registry
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > .npmrc
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
